---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: belenot/ui
        livenessProbe:
          periodSeconds: 1
          httpGet:
            path: /
            port: 8080
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  ui
spec:
  prefix: /
  # prefix_regex: true
  service: http://ui.default